<?php

if (!function_exists('testing_helper')) {
    function testing_helper($param) {
        return "My Testing : " . $param;
    }
}

// Countries Array 
function CountryArray(){
    $countries = [
        'AF' => 'Afghanistan',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua and Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, Democratic Republic',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island and McDonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KP' => 'Korea, Democratic People\'s Republic of',
        'KR' => 'Korea, Republic of',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People\'s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia, the former Yugoslav Republic of',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States of',
        'MD' => 'Moldova, Republic of',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestine, State of',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Réunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barthélemy',
        'SH' => 'Saint Helena, Ascension and Tristan da Cunha',
        'KN' => 'Saint Kitts and Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin (French part)',
        'PM' => 'Saint Pierre and Miquelon',
        'VC' => 'Saint Vincent and the Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome and Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SX' => 'Sint Maarten (Dutch part)',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia and the South Sandwich Islands',
        'SS' => 'South Sudan',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard and Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan, Province of China',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania, United Republic of',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks and Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UM' => 'United States Minor Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela, Bolivarian Republic of',
        'VN' => 'Viet Nam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.S.',
        'WF' => 'Wallis and Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe'
    ];

    return  $countries;
}

function CountryCodes()
{
    $countryCodes = [
        'AD' => '+376',  // Andorra
        'AE' => '+971',  // United Arab Emirates
        'AF' => '+93',   // Afghanistan
        'AG' => '+1-268',  // Antigua and Barbuda
        'AI' => '+1-264',  // Anguilla
        'AL' => '+355',  // Albania
        'AM' => '+374',  // Armenia
        'AO' => '+244',  // Angola
        'AQ' => '+672',  // Antarctica
        'AR' => '+54',   // Argentina
        'AS' => '+1-684',  // American Samoa
        'AT' => '+43',   // Austria
        'AU' => '+61',   // Australia
        'AW' => '+297',  // Aruba
        'AX' => '+358-18',  // Åland Islands
        'AZ' => '+994',  // Azerbaijan
        'BA' => '+387',  // Bosnia and Herzegovina
        'BB' => '+1-246',  // Barbados
        'BD' => '+880',  // Bangladesh
        'BE' => '+32',   // Belgium
        'BF' => '+226',  // Burkina Faso
        'BG' => '+359',  // Bulgaria
        'BH' => '+973',  // Bahrain
        'BI' => '+257',  // Burundi
        'BJ' => '+229',  // Benin
        'BL' => '+590',  // Saint Barthélemy
        'BM' => '+1-441',  // Bermuda
        'BN' => '+673',  // Brunei Darussalam
        'BO' => '+591',  // Bolivia (Plurinational State of)
        'BQ' => '+599',  // Bonaire, Sint Eustatius and Saba
        'BR' => '+55',   // Brazil
        'BS' => '+1-242',  // Bahamas
        'BT' => '+975',  // Bhutan
        'BV' => '+47',   // Bouvet Island
        'BW' => '+267',  // Botswana
        'BY' => '+375',  // Belarus
        'BZ' => '+501',  // Belize
        'CA' => '+1',    // Canada
        'CC' => '+61',   // Cocos (Keeling) Islands
        'CD' => '+243',  // Congo, Democratic Republic of the
        'CF' => '+236',  // Central African Republic
        'CG' => '+242',  // Congo
        'CH' => '+41',   // Switzerland
        'CI' => '+225',  // Côte d'Ivoire
        'CK' => '+682',  // Cook Islands
        'CL' => '+56',   // Chile
        'CM' => '+237',  // Cameroon
        'CN' => '+86',   // China
        'CO' => '+57',   // Colombia
        'CR' => '+506',  // Costa Rica
        'CU' => '+53',   // Cuba
        'CV' => '+238',  // Cabo Verde
        'CW' => '+599',  // Curaçao
        'CX' => '+61',   // Christmas Island
        'CY' => '+357',  // Cyprus
        'CZ' => '+420',  // Czech Republic
        'DE' => '+49',   // Germany
        'DJ' => '+253',  // Djibouti
        'DK' => '+45',   // Denmark
        'DM' => '+1-767',  // Dominica
        'DO' => '+1-809, 1-829, 1-849',  // Dominican Republic
        'DZ' => '+213',  // Algeria
        'EC' => '+593',  // Ecuador
        'EE' => '+372',  // Estonia
        'EG' => '+20',   // Egypt
        'EH' => '+212',  // Western Sahara
        'ER' => '+291',  // Eritrea
        'ES' => '+34',   // Spain
        'ET' => '+251',  // Ethiopia
        'FI' => '+358',  // Finland
        'FJ' => '+679',  // Fiji
        'FK' => '+500',  // Falkland Islands (Malvinas)
        'FM' => '+691',  // Micronesia (Federated States of)
        'FO' => '+298',  // Faroe Islands
        'FR' => '+33',   // France
        'GA' => '+241',  // Gabon
        'GB' => '+44',   // United Kingdom of Great Britain and Northern Ireland
        'GD' => '+1-473',  // Grenada
        'GE' => '+995',  // Georgia
        'GF' => '+594',  // French Guiana
        'GG' => '+44',   // Guernsey
        'GH' => '+233',  // Ghana
        'GI' => '+350',  // Gibraltar
        'GL' => '+299',  // Greenland
        'GM' => '+220',  // Gambia
        'GN' => '+224',  // Guinea
        'GP' => '+590',  // Guadeloupe
        'GQ' => '+240',  // Equatorial Guinea
        'GR' => '+30',   // Greece
        'GT' => '+502',  // Guatemala
        'GU' => '+1-671',  // Guam
        'GW' => '+245',  // Guinea-Bissau
        'GY' => '+592',  // Guyana
        'HK' => '+852',  // Hong Kong
        'HM' => '+672',  // Heard Island and McDonald Islands
        'HN' => '+504',  // Honduras
        'HR' => '+385',  // Croatia
        'HT' => '+509',  // Haiti
        'HU' => '+36',   // Hungary
        'ID' => '+62',   // Indonesia
        'IE' => '+353',  // Ireland
        'IL' => '+972',  // Israel
        'IM' => '+44',   // Isle of Man
        'IN' => '+91',   // India
        'IO' => '+246',  // British Indian Ocean Territory
        'IQ' => '+964',  // Iraq
        'IR' => '+98',   // Iran (Islamic Republic of)
        'IS' => '+354',  // Iceland
        'IT' => '+39',   // Italy
        'JE' => '+44',   // Jersey
        'JM' => '+1-876',  // Jamaica
        'JO' => '+962',  // Jordan
        'JP' => '+81',   // Japan
        'KE' => '+254',  // Kenya
        'KG' => '+996',  // Kyrgyzstan
        'KH' => '+855',  // Cambodia
        'KI' => '+686',  // Kiribati
        'KM' => '+269',  // Comoros
        'KN' => '+1-869',  // Saint Kitts and Nevis
        'KP' => '+850',  // Korea (Democratic People's Republic of)
        'KR' => '+82',   // Korea, Republic of
        'KW' => '+965',  // Kuwait
        'KY' => '+1-345',  // Cayman Islands
        'KZ' => '+7',    // Kazakhstan
        'LA' => '+856',  // Lao People's Democratic Republic
        'LB' => '+961',  // Lebanon
        'LC' => '+1-758',  // Saint Lucia
        'LI' => '+423',  // Liechtenstein
        'LK' => '+94',   // Sri Lanka
        'LR' => '+231',  // Liberia
        'LS' => '+266',  // Lesotho
        'LT' => '+370',  // Lithuania
        'LU' => '+352',  // Luxembourg
        'LV' => '+371',  // Latvia
        'LY' => '+218',  // Libya
        'MA' => '+212',  // Morocco
        'MC' => '+377',  // Monaco
        'MD' => '+373',  // Moldova, Republic of
        'ME' => '+382',  // Montenegro
        'MF' => '+590',  // Saint Martin (French part)
        'MG' => '+261',  // Madagascar
        'MH' => '+692',  // Marshall Islands
        'MK' => '+389',  // North Macedonia
        'ML' => '+223',  // Mali
        'MM' => '+95',   // Myanmar
        'MN' => '+976',  // Mongolia
        'MO' => '+853',  // Macao
        'MP' => '+1-670',  // Northern Mariana Islands
        'MQ' => '+596',  // Martinique
        'MR' => '+222',  // Mauritania
        'MS' => '+1-664',  // Montserrat
        'MT' => '+356',  // Malta
        'MU' => '+230',  // Mauritius
        'MV' => '+960',  // Maldives
        'MW' => '+265',  // Malawi
        'MX' => '+52',   // Mexico
        'MY' => '+60',   // Malaysia
        'MZ' => '+258',  // Mozambique
        'NA' => '+264',  // Namibia
        'NC' => '+687',  // New Caledonia
        'NE' => '+227',  // Niger
        'NF' => '+672',  // Norfolk Island
        'NG' => '+234',  // Nigeria
        'NI' => '+505',  // Nicaragua
        'NL' => '+31',   // Netherlands
        'NO' => '+47',   // Norway
        'NP' => '+977',  // Nepal
        'NR' => '+674',  // Nauru
        'NU' => '+683',  // Niue
        'NZ' => '+64',   // New Zealand
        'OM' => '+968',  // Oman
        'PA' => '+507',  // Panama
        'PE' => '+51',   // Peru
        'PF' => '+689',  // French Polynesia
        'PG' => '+675',  // Papua New Guinea
        'PH' => '+63',   // Philippines
        'PK' => '+92',   // Pakistan
        'PL' => '+48',   // Poland
        'PM' => '+508',  // Saint Pierre and Miquelon
        'PN' => '+870',  // Pitcairn
        'PR' => '+1-787, 1-939',  // Puerto Rico
        'PT' => '+351',  // Portugal
        'PW' => '+680',  // Palau
        'PY' => '+595',  // Paraguay
        'QA' => '+974',  // Qatar
        'RE' => '+262',  // Réunion
        'RO' => '+40',   // Romania
        'RS' => '+381',  // Serbia
        'RU' => '+7',    // Russian Federation
        'RW' => '+250',  // Rwanda
        'SA' => '+966',  // Saudi Arabia
        'SB' => '+677',  // Solomon Islands
        'SC' => '+248',  // Seychelles
        'SD' => '+249',  // Sudan
        'SE' => '+46',   // Sweden
        'SG' => '+65',   // Singapore
        'SH' => '+290',  // Saint Helena, Ascension and Tristan da Cunha
        'SI' => '+386',  // Slovenia
        'SJ' => '+47',   // Svalbard and Jan Mayen
        'SK' => '+421',  // Slovakia
        'SL' => '+232',  // Sierra Leone
        'SM' => '+378',  // San Marino
        'SN' => '+221',  // Senegal
        'SO' => '+252',  // Somalia
        'SR' => '+597',  // Suriname
        'SS' => '+211',  // South Sudan
        'ST' => '+239',  // Sao Tome and Principe
        'SV' => '+503',  // El Salvador
        'SX' => '+1-721',  // Sint Maarten (Dutch part)
        'SY' => '+963',  // Syrian Arab Republic
        'SZ' => '+268',  // Eswatini
        'TC' => '+1-649',  // Turks and Caicos Islands
        'TD' => '+235',  // Chad
        'TF' => '+262',  // French Southern Territories
        'TG' => '+228',  // Togo
        'TH' => '+66',   // Thailand
        'TJ' => '+992',  // Tajikistan
        'TK' => '+690',  // Tokelau
        'TL' => '+670',  // Timor-Leste
        'TM' => '+993',  // Turkmenistan
        'TN' => '+216',  // Tunisia
        'TO' => '+676',  // Tonga
        'TR' => '+90',   // Turkey
        'TT' => '+1-868',  // Trinidad and Tobago
        'TV' => '+688',  // Tuvalu
        'TW' => '+886',  // Taiwan, Province of China
        'TZ' => '+255',  // Tanzania, United Republic of
        'UA' => '+380',  // Ukraine
        'UG' => '+256',  // Uganda
        'UM' => '+1',    // United States Minor Outlying Islands
        'US' => '+1',    // United States of America
        'UY' => '+598',  // Uruguay
        'UZ' => '+998',  // Uzbekistan
        'VA' => '+379',  // Holy See
        'VC' => '+1-784',  // Saint Vincent and the Grenadines
        'VE' => '+58',   // Venezuela (Bolivarian Republic of)
        'VG' => '+1-284',  // Virgin Islands (British)
        'VI' => '+1-340',  // Virgin Islands (U.S.)
        'VN' => '+84',   // Viet Nam
        'VU' => '+678',  // Vanuatu
        'WF' => '+681',  // Wallis and Futuna
        'WS' => '+685',  // Samoa
        'YE' => '+967',  // Yemen
        'YT' => '+262',  // Mayotte
        'ZA' => '+27',   // South Africa
        'ZM' => '+260',  // Zambia
        'ZW' => '+263',  // Zimbabwe
    ];

    return $countryCodes;
}